config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations] 
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :organizations, only: [:show] do
    collection do
      post 'remove_user/:user_id', to: 'organizations#remove_from_organization', as: 'remove_user'
    end
  end
  resources :orders, only: [:new, :create, :update, :index, :show, :edit] do
    resources :transport_loads, only: [:new, :create]
  end
  resources :address_books, only: [:index, :create, :destroy]
  namespace :admin do
    get 'user_management', to: 'user_management#index'
  end
  namespace :management do
    get 'index', to: 'organizations#index'
  end
  # named user so as not to conflict with devise
  resources :user, only: [:create, :edit, :update], controller: 'users'

  # These are all routes for the template and should be omitted for production
  get 'template', to: "templates#Dashboard.Default"
  get 'Apps.Chat', to: "templates#Apps.Chat"
  get 'Apps.MediaLibrary.ViewAudio', to: "templates#Apps.MediaLibrary.ViewAudio"
  get 'Apps.MediaLibrary.ViewFolder', to: "templates#Apps.MediaLibrary.ViewFolder"
  get 'Apps.MediaLibrary.ViewImage', to: "templates#Apps.MediaLibrary.ViewImage"
  get 'Apps.MediaLibrary.ViewVideo', to: "templates#Apps.MediaLibrary.ViewVideo"
  get 'Apps.Survey', to: "templates#Apps.Survey"
  get 'Apps.Survey.List', to: "templates#Apps.Survey.List"
  get 'Apps.Todo.Details', to: "templates#Apps.Todo.Details"
  get 'Apps.Todo.List', to: "templates#Apps.Todo.List"
  get 'Dashboard.Default', to: "templates#Dashboard.Default"
  get 'Blank.Page', to: "templates#Blank.Page"
  get 'Dashboard.Analytics', to: "templates#Dashboard.Analytics"
  get 'Dashboard.Content', to: "templates#Dashboard.Content"
  get 'Dashboard.Default', to: "templates#Dashboard.Default"
  get 'Dashboard.Ecommerce', to: "templates#Dashboard.Ecommerce"
  get 'Menu.Default', to: "templates#Menu.Default"
  get 'Menu.Hidden', to: "templates#Menu.Hidden"
  get 'Menu.Mainhidden', to: "templates#Menu.Mainhidden"
  get 'Menu.Subhidden', to: "templates#Menu.Subhidden"
  get 'Pages.Auth.ForgotPassword', to: "templates#Pages.Auth.ForgotPassword"
  get 'Pages.Auth.Login', to: "templates#Pages.Auth.Login"
  get 'Pages.Auth.Register', to: "templates#Pages.Auth.Register"
  get 'Pages.Blog.Detail.Alt', to: "templates#Pages.Blog.Detail.Alt"
  get 'Pages.Blog.Detail', to: "templates#Pages.Blog.Detail"
  get 'Pages.Blog', to: "templates#Pages.Blog"
  get 'Pages.Misc.Coming.Soon', to: "templates#Pages.Misc.Coming.Soon"
  get 'Pages.Misc.Error', to: "templates#Pages.Misc.Error"
  get 'Pages.Misc.Faq', to: "templates#Pages.Misc.Faq"
  get 'Pages.Misc.Invoice', to: "templates#Pages.Misc.Invoice"
  get 'Pages.Misc.Invoice.Standalone', to: "templates#Pages.Misc.Invoice.Standalone"
  get 'Pages.Misc.Knowledge.Base', to: "templates#Pages.Misc.Knowledge.Base"
  get 'Pages.Misc.Mailing', to: "templates#Pages.Misc.Mailing"
  get 'Pages.Misc.Mailing.Standalone', to: "templates#Pages.Misc.Mailing.Standalone"
  get 'Pages.Misc.Maintenance', to: "templates#Pages.Misc.Maintenance"
  get 'Pages.Misc.Pricing', to: "templates#Pages.Misc.Pricing"
  get 'Pages.Misc.Search', to: "templates#Pages.Misc.Search"
  get 'Pages.Product.Detail', to: "templates#Pages.Product.Detail"
  get 'Pages.Product.Images', to: "templates#Pages.Product.Images"
  get 'Pages.Product.List', to: "templates#Pages.Product.List"
  get 'Pages.Product.Thumbs', to: "templates#Pages.Product.Thumbs"
  get 'Pages.Profile.Portfolio', to: "templates#Pages.Profile.Portfolio"
  get 'Pages.Profile.Social', to: "templates#Pages.Profile.Social"
  get 'Ui.Components.Alerts', to: "templates#Ui.Components.Alerts"
  get 'Ui.Components.Badges', to: "templates#Ui.Components.Badges"
  get 'Ui.Components.Buttons', to: "templates#Ui.Components.Buttons"
  get 'Ui.Components.Cards', to: "templates#Ui.Components.Cards"
  get 'Ui.Components.Carousel', to: "templates#Ui.Components.Carousel"
  get 'Ui.Components.Charts', to: "templates#Ui.Components.Charts"
  get 'Ui.Components.Collapse', to: "templates#Ui.Components.Collapse"
  get 'Ui.Components.Dropdowns', to: "templates#Ui.Components.Dropdowns"
  get 'Ui.Components.Editors', to: "templates#Ui.Components.Editors"
  get 'Ui.Components.Icons', to: "templates#Ui.Components.Icons"
  get 'Ui.Components.InputGroups', to: "templates#Ui.Components.InputGroups"
  get 'Ui.Components.Jumbotron', to: "templates#Ui.Components.Jumbotron"
  get 'Ui.Components.Modal', to: "templates#Ui.Components.Modal"
  get 'Ui.Components.Navigation', to: "templates#Ui.Components.Navigation"
  get 'Ui.Components.PopoverandTooltip', to: "templates#Ui.Components.PopoverandTooltip"
  get 'Ui.Components.Sortable', to: "templates#Ui.Components.Sortable"
  get 'Ui.Components.Tables', to: "templates#Ui.Components.Tables"
  get 'Ui.Datatables.Default', to: "templates#Ui.Datatables.Default"
  get 'Ui.Datatables.Pagination', to: "templates#Ui.Datatables.Pagination"
  get 'Ui.Datatables.Rows', to: "templates#Ui.Datatables.Rows"
  get 'Ui.Datatables.Scroll', to: "templates#Ui.Datatables.Scroll"
  get 'Ui.Forms.Components', to: "templates#Ui.Forms.Components"
  get 'Ui.Forms.Layouts', to: "templates#Ui.Forms.Layouts"
  get 'Ui.Forms.Validation', to: "templates#Ui.Forms.Validation"
  get 'Ui.Forms.Wizard', to: "templates#Ui.Forms.Wizard"
end

app/controllers/admin/user_management_controller.rb
module Admin
  class UserManagementController < ApplicationController
    before_action :org_admin?

    def index
      @users = current_user.orgainzation_members
      @organization = nil

      # if org id params exist and user is an contaynor employee
      if params[:org_id].present? && current_user.contaynor_employee?
        @organization = Organization.find(params[:org_id])
        @users = @organization.users
      end
    end
  end
end

app/views/admin/user_management/_add_user_modal.html.erb
<div class="modal fade modal-right" id="add_user_modal" tabindex="-1" role="dialog" aria-labelledby="add_user_modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add New User To Your Organization</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <%= simple_form_for User.new, url: {controller: '/users', action: "create"}, html: { autocomplete: 'off' } do |f| %>
              <div class="modal-body">
                <%= f.input :first_name, placeholder: "Enter first name", required: true %>
                <%= f.input :last_name, placeholder: "Enter last name", required: true %>
                <%= f.input :email, placeholder: "Enter email", required: true %>
                <%= f.input :company_role, placeholder: "Enter company role" %>
                <%= f.input :telephone_number, placeholder: "Enter telephone number" %>

                <%= f.input :employee_admin, as: :boolean, label: 'Make user employee admin', class: "form-check-input radio_buttons" %>
                <%= f.input :organization_admin, as: :boolean, label: 'Make user organization admin' %>
                <%= f.input :master_admin, as: :boolean, label: 'Make user master admin', class: "form-check-input radio_buttons" %>
                <%= f.input :dark_theme, as: :boolean, label: 'Assign dark theme' %>
                <%= f.input :org_id, as: :hidden, input_html: { value: params[:org_id] } %>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
                <%= f.submit "Submit", class: 'btn btn-primary' %>
              </div>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/user_management/index.html.erb
<main>
  <div class="container-fluid disable-text-selection">
      <div class="row">
          <div class="col-12">
              <div class="mb-2">
                  <h1>User Management</h1>
                  <div class="top-right-button-container">
                      <button type="button" class="btn btn-primary btn-lg top-right-button mr-1" data-toggle="modal" data-backdrop="static" data-target="#add_user_modal">ADD NEW USER TO ORGANIZATION</button>
                  </div>
                  <% unless @organization.nil? %>
                    <h3>Organization: <%= @organization.name %></h3>
                  <% end %>
              </div>
          </div>
      </div>
      <%= render 'add_user_modal' %>
      <div class="row">
          <div class="col-12 list" data-check-all="checkAll">
              <div class="d-flex flex-row">
                  <div class="d-flex flex-grow-1 min-width-zero">
                      <div
                          class="card-body align-self-center d-flex flex-column flex-md-row justify-content-between min-width-zero align-items-md-center">
                          <p class="list-item-heading mb-0 truncate w-15 w-xs-100">Name</p>
                          <p class="list-item-heading mb-0 truncate w-10 w-xs-100">Email</p>
                          <p class="list-item-heading mb-0 truncate w-10 w-xs-100">Phone number</p>
                          <p class="list-item-heading mb-0 truncate w-10 w-xs-100">Action</p>
                          <% if params[:org_id].present? && current_user.contaynor_employee? %>
                            <p class="list-item-heading mb-0 truncate w-5 w-xs-100"></p>
                          <% end %>
                      </div>
                  </div>
              </div>
          </div>
      </div>
      <div class="separator mb-5"></div>
      <% @users.each do |user| %>
        <div class="row">
            <div class="col-12 list" data-check-all="checkAll">
                <div class="card d-flex flex-row mb-3">
                    <div class="d-flex flex-grow-1 min-width-zero">
                        <div
                            class="card-body align-self-center d-flex flex-column flex-md-row justify-content-between min-width-zero align-items-md-center">
                            <p class="list-item-heading mb-0 truncate w-15 w-xs-100" title="<%= user.name %>">
                              <%= user.name %>
                            </p>
                            <p class="list-item-heading mb-0 truncate w-15 w-xs-100" title="<%= user.email %>">
                              <%= user.email %>
                            </p>
                            <p class="list-item-heading mb-0 truncate w-10 w-xs-100" title="<%= user.telephone_number %>">
                              <%= user.telephone_number.present? ? user.telephone_number : 'N/A' %>
                            </p>
                            <div class="w-10 w-xs-100">
                                <%= link_to 'Remove', remove_user_organizations_path(user_id: user.id), class: 'btn btn-danger', method: :post %>
                            </div>
                            <% if params[:org_id].present? && current_user.contaynor_employee? %>
                                <div class="w-5 w-xs-100 align-self-center d-flex flex-column flex-md-row justify-content-between min-width-zero align-items-md-center">
                                    <%= link_to "Edit", edit_user_path(id: user.id), class: "btn btn-info btn-sm" %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      <% end %>
  </div>
</main>