config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations] 
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :organizations, only: [:show] do
    collection do
      post 'remove_user/:user_id', to: 'organizations#remove_from_organization', as: 'remove_user'
    end
  end
  resources :orders, only: [:new, :create, :update, :index, :show, :edit] do
    resources :transport_loads, only: [:new, :create]
  end
  resources :address_books, only: [:index, :create, :destroy]
  namespace :admin do
    get 'user_management', to: 'user_management#index'
  end
  namespace :management do
    get 'index', to: 'organizations#index'
  end
  # named user so as not to conflict with devise
  resources :user, only: [:create, :edit, :update], controller: 'users'

  # These are all routes for the template and should be omitted for production
  get 'template', to: "templates#Dashboard.Default"
  get 'Apps.Chat', to: "templates#Apps.Chat"
  get 'Apps.MediaLibrary.ViewAudio', to: "templates#Apps.MediaLibrary.ViewAudio"
  get 'Apps.MediaLibrary.ViewFolder', to: "templates#Apps.MediaLibrary.ViewFolder"
  get 'Apps.MediaLibrary.ViewImage', to: "templates#Apps.MediaLibrary.ViewImage"
  get 'Apps.MediaLibrary.ViewVideo', to: "templates#Apps.MediaLibrary.ViewVideo"
  get 'Apps.Survey', to: "templates#Apps.Survey"
  get 'Apps.Survey.List', to: "templates#Apps.Survey.List"
  get 'Apps.Todo.Details', to: "templates#Apps.Todo.Details"
  get 'Apps.Todo.List', to: "templates#Apps.Todo.List"
  get 'Dashboard.Default', to: "templates#Dashboard.Default"
  get 'Blank.Page', to: "templates#Blank.Page"
  get 'Dashboard.Analytics', to: "templates#Dashboard.Analytics"
  get 'Dashboard.Content', to: "templates#Dashboard.Content"
  get 'Dashboard.Default', to: "templates#Dashboard.Default"
  get 'Dashboard.Ecommerce', to: "templates#Dashboard.Ecommerce"
  get 'Menu.Default', to: "templates#Menu.Default"
  get 'Menu.Hidden', to: "templates#Menu.Hidden"
  get 'Menu.Mainhidden', to: "templates#Menu.Mainhidden"
  get 'Menu.Subhidden', to: "templates#Menu.Subhidden"
  get 'Pages.Auth.ForgotPassword', to: "templates#Pages.Auth.ForgotPassword"
  get 'Pages.Auth.Login', to: "templates#Pages.Auth.Login"
  get 'Pages.Auth.Register', to: "templates#Pages.Auth.Register"
  get 'Pages.Blog.Detail.Alt', to: "templates#Pages.Blog.Detail.Alt"
  get 'Pages.Blog.Detail', to: "templates#Pages.Blog.Detail"
  get 'Pages.Blog', to: "templates#Pages.Blog"
  get 'Pages.Misc.Coming.Soon', to: "templates#Pages.Misc.Coming.Soon"
  get 'Pages.Misc.Error', to: "templates#Pages.Misc.Error"
  get 'Pages.Misc.Faq', to: "templates#Pages.Misc.Faq"
  get 'Pages.Misc.Invoice', to: "templates#Pages.Misc.Invoice"
  get 'Pages.Misc.Invoice.Standalone', to: "templates#Pages.Misc.Invoice.Standalone"
  get 'Pages.Misc.Knowledge.Base', to: "templates#Pages.Misc.Knowledge.Base"
  get 'Pages.Misc.Mailing', to: "templates#Pages.Misc.Mailing"
  get 'Pages.Misc.Mailing.Standalone', to: "templates#Pages.Misc.Mailing.Standalone"
  get 'Pages.Misc.Maintenance', to: "templates#Pages.Misc.Maintenance"
  get 'Pages.Misc.Pricing', to: "templates#Pages.Misc.Pricing"
  get 'Pages.Misc.Search', to: "templates#Pages.Misc.Search"
  get 'Pages.Product.Detail', to: "templates#Pages.Product.Detail"
  get 'Pages.Product.Images', to: "templates#Pages.Product.Images"
  get 'Pages.Product.List', to: "templates#Pages.Product.List"
  get 'Pages.Product.Thumbs', to: "templates#Pages.Product.Thumbs"
  get 'Pages.Profile.Portfolio', to: "templates#Pages.Profile.Portfolio"
  get 'Pages.Profile.Social', to: "templates#Pages.Profile.Social"
  get 'Ui.Components.Alerts', to: "templates#Ui.Components.Alerts"
  get 'Ui.Components.Badges', to: "templates#Ui.Components.Badges"
  get 'Ui.Components.Buttons', to: "templates#Ui.Components.Buttons"
  get 'Ui.Components.Cards', to: "templates#Ui.Components.Cards"
  get 'Ui.Components.Carousel', to: "templates#Ui.Components.Carousel"
  get 'Ui.Components.Charts', to: "templates#Ui.Components.Charts"
  get 'Ui.Components.Collapse', to: "templates#Ui.Components.Collapse"
  get 'Ui.Components.Dropdowns', to: "templates#Ui.Components.Dropdowns"
  get 'Ui.Components.Editors', to: "templates#Ui.Components.Editors"
  get 'Ui.Components.Icons', to: "templates#Ui.Components.Icons"
  get 'Ui.Components.InputGroups', to: "templates#Ui.Components.InputGroups"
  get 'Ui.Components.Jumbotron', to: "templates#Ui.Components.Jumbotron"
  get 'Ui.Components.Modal', to: "templates#Ui.Components.Modal"
  get 'Ui.Components.Navigation', to: "templates#Ui.Components.Navigation"
  get 'Ui.Components.PopoverandTooltip', to: "templates#Ui.Components.PopoverandTooltip"
  get 'Ui.Components.Sortable', to: "templates#Ui.Components.Sortable"
  get 'Ui.Components.Tables', to: "templates#Ui.Components.Tables"
  get 'Ui.Datatables.Default', to: "templates#Ui.Datatables.Default"
  get 'Ui.Datatables.Pagination', to: "templates#Ui.Datatables.Pagination"
  get 'Ui.Datatables.Rows', to: "templates#Ui.Datatables.Rows"
  get 'Ui.Datatables.Scroll', to: "templates#Ui.Datatables.Scroll"
  get 'Ui.Forms.Components', to: "templates#Ui.Forms.Components"
  get 'Ui.Forms.Layouts', to: "templates#Ui.Forms.Layouts"
  get 'Ui.Forms.Validation', to: "templates#Ui.Forms.Validation"
  get 'Ui.Forms.Wizard', to: "templates#Ui.Forms.Wizard"
end

app/views/shared/navbar/_index.html.erb
<nav class="navbar fixed-top">
  <div class="d-flex align-items-center navbar-left">
    <%= render 'shared/navbar/menu_toggle' %>
  </div>
  <%= link_to root_path, class: "navbar-logo" do %>
      <span class="logo d-none d-xs-block"></span>
      <span class="logo-mobile d-block d-xs-none"></span>
  <% end %>
  <div class="navbar-right">
    <div class="header-icons d-inline-block align-middle">
      <%#= render 'shared/navbar/notifications' %>
      <button class="header-icon btn btn-empty d-none d-sm-inline-block" type="button" id="fullScreenButton">
          <i class="simple-icon-size-fullscreen"></i>
          <i class="simple-icon-size-actual"></i>
      </button>
    </div>
    <div class="user d-inline-block">
      <button class="btn btn-empty p-0" type="button" data-toggle="dropdown" aria-haspopup="true"
    aria-expanded="false">
        <span class="name"><%= current_user.name %></span>
        <span>
          <% if current_user.contaynor_employee? %>
            <%= image_tag "profile.jpg" %>
          <% else %>
            <%= image_tag "client.jpg" %>
          <% end %>
        </span>
      </button>
      <div class="dropdown-menu dropdown-menu-right mt-3">
          <% if current_user.contaynor_employee? %>
            <%= link_to 'Management Dashboard', management_index_path, class: 'dropdown-item' %>
          <% end %>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/navbar/_menu_toggle.html.erb
<a href="#" class="menu-button d-none d-md-block">
    <svg class="main" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 9 17">
        <rect x="0.48" y="0.5" width="7" height="1" />
        <rect x="0.48" y="7.5" width="7" height="1" />
        <rect x="0.48" y="15.5" width="7" height="1" />
    </svg>
    <svg class="sub" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 17">
        <rect x="1.56" y="0.5" width="16" height="1" />
        <rect x="1.56" y="7.5" width="16" height="1" />
        <rect x="1.56" y="15.5" width="16" height="1" />
    </svg>
</a>
<a href="#" class="menu-button-mobile d-xs-block d-sm-block d-md-none">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26 17">
      <rect x="0.5" y="0.5" width="25" height="1" />
      <rect x="0.5" y="7.5" width="25" height="1" />
      <rect x="0.5" y="15.5" width="25" height="1" />
  </svg>
</a>

app/views/shared/navbar/_notifications.html.erb
<div class="position-relative d-inline-block">
  <button class="header-icon btn btn-empty" type="button" id="notificationButton"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="simple-icon-bell"></i>
    <span class="count">3</span>
  </button>
  <div class="dropdown-menu dropdown-menu-right mt-3 position-absolute" id="notificationDropdown">
      <div class="scroll">
          <div class="d-flex flex-row mb-3 pb-3 border-bottom">
              <a href="#">
                  <img src="img/profile-pic-l-2.jpg" alt="Notification Image"
                      class="img-thumbnail list-thumbnail xsmall border-0 rounded-circle" />
              </a>
              <div class="pl-3">
                  <a href="#">
                      <p class="font-weight-medium mb-1">Joisse Kaycee just sent a new comment!</p>
                      <p class="text-muted mb-0 text-small">09.04.2018 - 12:45</p>
                  </a>
              </div>
          </div>
          <div class="d-flex flex-row mb-3 pb-3 border-bottom">
              <a href="#">
                  <img src="img/notification-thumb.jpg" alt="Notification Image"
                      class="img-thumbnail list-thumbnail xsmall border-0 rounded-circle" />
              </a>
              <div class="pl-3">
                  <a href="#">
                      <p class="font-weight-medium mb-1">1 item is out of stock!</p>
                      <p class="text-muted mb-0 text-small">09.04.2018 - 12:45</p>
                  </a>
              </div>
          </div>
          <div class="d-flex flex-row mb-3 pb-3 border-bottom">
              <a href="#">
                  <img src="img/notification-thumb-2.jpg" alt="Notification Image"
                      class="img-thumbnail list-thumbnail xsmall border-0 rounded-circle" />
              </a>
              <div class="pl-3">
                  <a href="#">
                      <p class="font-weight-medium mb-1">New order received! It is total $147,20.</p>
                      <p class="text-muted mb-0 text-small">09.04.2018 - 12:45</p>
                  </a>
              </div>
          </div>
          <div class="d-flex flex-row mb-3 pb-3 ">
              <a href="#">
                  <img src="img/notification-thumb-3.jpg" alt="Notification Image"
                      class="img-thumbnail list-thumbnail xsmall border-0 rounded-circle" />
              </a>
              <div class="pl-3">
                  <a href="#">
                      <p class="font-weight-medium mb-1">3 items just added to wish list by a user!
                      </p>
                      <p class="text-muted mb-0 text-small">09.04.2018 - 12:45</p>
                  </a>
              </div>
          </div>
      </div>
  </div>
</div>